# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 10
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.2.0
      with:
        node-version: 12.16.3
    - name: Install appium 
      run: npm install -g appium
    - name: Run Appium
      run: appium
    - name: Open Emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
          api-level: 30
          script: ./gradlew connectedCheck
    - name: Build with Maven
      run: mvn clean verify -Dtestng.dtd.http=true
      
