# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macOS-latest
    strategy: # we are using strategy if we need to run on parallel with different devices and version
      matrix:
        api-level: [25] #Google api level for example [25,23,28] 
        target: [default]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 9
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.2.0
      with:
        node-version: 12.16.3
    - name: Clean Packages 
#       run: |
#           rm -rf node_modules
#           npm cache clean --force
#           rm -rf package-lock.json
      run: |
          npm install -g appium
          appium -v
          appium &  
    - name: Run Appium Tests
      uses: reactivecircus/android-emulator-runner@v1 # install and create the Emulator
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: x86_64
        profile: Nexus 6
        script: mvn clean verify -Dtesting.dtd.http=true --info # running our test with info to check the results
    - name: Run ADB Tests
      run: adb devices
  
   
